### ISSUE TITLE
RuntimeError: release unlocked lock

### ISSUE THREAD

**Issue by cybe** [ChristianKuehnel/btlewrap#13]
Hi @ChristianKuehnel,

This is a follow up on #8. The program flow somehow tries to release an [unreleased lock](https://github.com/ChristianKuehnel/btlewrap/blob/1e9a3989a58aa631d42deeb818d95769095195d9/btlewrap/base.py#L48). I'm not sure what the originating cause of this could be, as the lock must have been previously acquired successfully. It may be some kind of race condition or concurrency issue. We could potentially just test if the lock is actually acquired. What do you think?

Stack-trace of the exception:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/btlewrap/bluepy.py", line 26, in _func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/btlewrap/bluepy.py", line 55, in connect
    self._peripheral = Peripheral(mac, iface=iface)
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral C4:7C:8D:66:E3:CC, addr type: public

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/btlewrap/base.py", line 44, in __enter__
    self._backend.connect(self._mac)
  File "/usr/local/lib/python3.7/site-packages/btlewrap/bluepy.py", line 32, in _func_wrapper
    raise BluetoothBackendException() from last_error
btlewrap.base.BluetoothBackendException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gateway.py", line 57, in <module>
    raise e
  File "gateway.py", line 47, in <module>
    mqtt.publish(_WORKERS_QUEUE.get(timeout=10).execute())
  File "/bt-mqtt-gateway/workers_manager.py", line 32, in execute
    messages = self._callback(*self._args)
  File "/bt-mqtt-gateway/workers/miflora.py", line 30, in status_update
    ret += self.update_device_state(name, poller)
  File "/bt-mqtt-gateway/workers/miflora.py", line 39, in update_device_state
    ret.append(MqttMessage(topic=self.format_topic(name, attr), payload=poller.parameter_value(attr)))
  File "/usr/local/lib/python3.7/site-packages/miflora/miflora_poller.py", line 132, in parameter_value
    self.fill_cache()
  File "/usr/local/lib/python3.7/site-packages/miflora/miflora_poller.py", line 68, in fill_cache
    with self._bt_interface.connect(self._mac) as connection:
  File "/usr/local/lib/python3.7/site-packages/btlewrap/base.py", line 47, in __enter__
    self._lock.release()
RuntimeError: release unlocked lock
```

**Comment by ChristianKuehnel** [comment]
Yes , that might solve the symptoms, but not the root cause. To be honest I would prefer to understand the root cause of this. The lock was intended to prevent exactly those concurrency issues...

**Comment by cybe** [comment]
Yeah, I'm on the same page.

**Comment by cybe** [comment]
I managed to [reproduce](https://gist.github.com/cybe/fe0edc27e3a3a4dc8c652425679ec630) the issue. It is caused by unlocking the lock twice from within the same thread. Here is what happens (_t_ stands for thread):

- _t1_ acquires the lock successfully
- _t2_ waits on `acquire()`
- _t1_ receives an exception and releases the lock
- _t2_ acquires the lock successfully
- _t1_ releases the lock **again** in `__del__`: `_BackendConnection.is_connected()` is true, because the lock is locked by _t2_. This is the root issue.
- _t2_ receives an exception and releases the lock. But it was already released by _t1_ beforehand. Hence the `RuntimeError: release unlocked lock`

I guess we could make sure to release a lock only once per thread like [this](https://github.com/cybe/btlewrap/commit/2ef0f932ba65962c112174237a6db97d549097b5).

**Comment by ChristianKuehnel** [comment]
@cybe sounds plausible. Does this solve the problem on your machine?
If so: feel free to create a PR

**Comment by cybe** [comment]
> Does this solve the problem on your machine? If so: feel free to create a PR

Let me test this for a week or two.
