### ISSUE TITLE
Fix Bluepy BrokenPipeError 

### ISSUE THREAD

**Issue by alemuro** [ChristianKuehnel/btlewrap#14]
Hello everyone 👋  

Seems that there is an error in the `bluepy` Python library used by `btlewrap` that produces a BrokenPipe error when the execution is being stopped by another thread/execution. 

This is the stacktrace (used in home-assistant):

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 261, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 441, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/beewi_smartclim/sensor.py", line 101, in update
    self._poller.update_sensor()
  File "/usr/local/lib/python3.7/site-packages/beewi_smartclim/__init__.py", line 75, in update_sensor
    with bt_interface.connect(self._mac) as connection:
  File "/usr/local/lib/python3.7/site-packages/btlewrap/base.py", line 44, in __enter__
    self._backend.connect(self._mac)
  File "/usr/local/lib/python3.7/site-packages/btlewrap/bluepy.py", line 26, in _func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/btlewrap/bluepy.py", line 55, in connect
    self._peripheral = Peripheral(mac, iface=iface)
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 431, in _connect
    self._writeCmd("conn %s %s %s\n" % (addr, addrType, "hci"+str(iface)))
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 305, in _writeCmd
    self._helper.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

I suggest to update the `bluepy` library version from `1.1.4` to `1.3.0`. https://github.com/ChristianKuehnel/btlewrap/blob/1b7aec934529dcf03f5ecdccd0b09c25c389974f/requirements.txt#L1

As they commented into an issue, this should be fixed after version `1.2.0`. 
https://github.com/IanHarvey/bluepy/issues/282#issuecomment-409303009

Thanks!

**Comment by alemuro** [comment]
Thanks @ChristianKuehnel. Please, can you release a new version to PyPi?
