### ISSUE TITLE
NoneType object has not attribute 'disconnect'.

### ISSUE THREAD

**Issue by jeroenterheerdt** [ChristianKuehnel/btlewrap#3]
I am using bt-mqtt-gateway that depends on btlewrap and found an issue that seems to be coming from btlewrap.

Trace:
```
Starting
Added: miflora with 30 seconds interval
Subscribing to: homeassistant/status with command: update_all
Updating all workers
[{'topic': 'miflora/orchid/temperature', 'payload': 23.4}, {'topic': 'miflora/orchid/moisture', 'payload': 80}, {'topic': 'miflora/orchid/light', 'payload': 2449}, {'topic': 'miflora/orchid/conductivity', 'payload': 3488}, {'topic': 'miflora/orchid/battery', 'payload': 96}]
Exception ignored in: <bound method BluetoothInterface.__del__ of <btlewrap.base.BluetoothInterface object at 0x75973490>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/btlewrap/base.py", line 17, in __del__
    self._backend.disconnect()
  File "/usr/local/lib/python3.6/site-packages/btlewrap/bluepy.py", line 26, in _func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/btlewrap/bluepy.py", line 60, in disconnect
    self._peripheral.disconnect()
AttributeError: 'NoneType' object has no attribute 'disconnect'
[]
```
Thread about bt-mqtt-gateway: https://github.com/zewelor/bt-mqtt-gateway/issues/14.

**Comment by ChristianKuehnel** [comment]
I just added a fix on the master branch. Please check if that solves your issue. I will then create a new release.

**Comment by ChristianKuehnel** [comment]
did not hear anything on this bug --> closing the issue.

**Comment by jeroenterheerdt** [comment]
It seems fixed. Thanks.
