### ISSUE TITLE
Get BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by aqualx** [ChristianKuehnel/btlewrap#9]
What is a proper solution to deal with such error?
I'm using btlewrap in my fork of miflora-mqtt-daemon and after some time (totally unpredictable) see crash of daemon with:
```
"Feb 16 06:17:45 wb miflora-mqtt-daemon.py[31469]: Exception ignored in: <bound method _BackendConnection.__del__ of <btlewrap.base._BackendConnection object
Feb 16 06:17:45 wb miflora-mqtt-daemon.py[31469]: Traceback (most recent call last):
Feb 16 06:17:45 wb miflora-mqtt-daemon.py[31469]:   File "/usr/local/lib/python3.5/dist-packages/btlewrap/base.py", line 54, in __del__
Feb 16 06:17:45 wb miflora-mqtt-daemon.py[31469]:     self._cleanup()
Feb 16 06:17:45 wb miflora-mqtt-daemon.py[31469]:   File "/usr/local/lib/python3.5/dist-packages/btlewrap/base.py", line 58, in _cleanup
Feb 16 06:17:45 wb miflora-mqtt-daemon.py[31469]:     self._backend.disconnect()
Feb 16 06:17:45 wb miflora-mqtt-daemon.py[31469]:   File "/usr/local/lib/python3.5/dist-packages/btlewrap/bluepy.py", line 26, in _func_wrapper
Feb 16 06:17:45 wb miflora-mqtt-daemon.py[31469]:     return func(*args, **kwargs)
Feb 16 06:17:45 wb miflora-mqtt-daemon.py[31469]:   File "/usr/local/lib/python3.5/dist-packages/btlewrap/bluepy.py", line 63, in disconnect
Feb 16 06:17:45 wb miflora-mqtt-daemon.py[31469]:     self._peripheral.disconnect()
Feb 16 06:17:45 wb miflora-mqtt-daemon.py[31469]:   File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 453, in disconnect
Feb 16 06:17:45 wb miflora-mqtt-daemon.py[31469]:     self._writeCmd("disc\n")
Feb 16 06:17:45 wb miflora-mqtt-daemon.py[31469]:   File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 305, in _writeCmd
Feb 16 06:17:45 wb miflora-mqtt-daemon.py[31469]:     self._helper.stdin.flush()
Feb 16 06:17:45 wb miflora-mqtt-daemon.py[31469]: BrokenPipeError: [Errno 32] Broken pipe"
```

Also in dmseg there is such error:
`[40293.568271] Bluetooth: hci0 ACL packet for unknown connection handle 16`

PS: Maybe this is something wrong with bluepy or somewhere we need add [ignore](https://www.quora.com/How-can-you-avoid-a-broken-pipe-error-on-Python)

**Comment by ChristianKuehnel** [comment]
I do not really have an idea what is causing this. It's an exception from bluepy. I'm not sure what we can do in btlewrap about this...

Best guess: It's a transmission error due to a bad connection between the Bluetooth dongle and the device.
